CREATE TABLE Daily_Progress (
    Id UUID PRIMARY KEY,
    UserId UUID REFERENCES Users(Id) ON DELETE CASCADE NOT NULL,
    TaskID UUID REFERENCES Daily_Tasks(Id) NOT NULL,
    CompletionDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Progress BIT(2) NOT NULL DEFAULT B'00'::bit(2)
);
