CREATE TABLE ThemeObjectives (
    Id UUID PRIMARY KEY,
    UserId UUID REFERENCES Users(Id) ON DELETE CASCADE NOT NULL,
    ThemeId UUID REFERENCES Themes(Id) ON DELETE CASCADE NOT NULL,
    Description VARCHAR(255) NOT NULL
);
